FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG AZURE_STORAGE_CONNECTION_STRING
ARG AZURE_STORAGE_CONTAINER_NAME
ARG COSMOS_ENDPOINT
ARG COSMOS_KEY
ARG COSMOS_DATABASE_NAME
ARG COSMOS_CONTAINER_NAME

ENV AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING
ENV AZURE_STORAGE_CONTAINER_NAME=$AZURE_STORAGE_CONTAINER_NAME
ENV COSMOS_ENDPOINT=$COSMOS_ENDPOINT
ENV COSMOS_KEY=$COSMOS_KEY
ENV COSMOS_DATABASE_NAME=$COSMOS_DATABASE_NAME
ENV COSMOS_CONTAINER_NAME=$COSMOS_CONTAINER_NAME

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]